export function translateToUrdu(text: string): string {
  // Simple translation logic using the dictionary
  const words = text.toLowerCase().split(/\s+/)
  const translatedWords = words.map((word) => {
    return englishToUrdu[word] || word // Use dictionary or keep original word
  })

  return translatedWords.join(" ")
}

// English to Urdu translation dictionary
const englishToUrdu: Record<string, string> = {
  // Common words
  the: "یہ",
  and: "اور",
  is: "ہے",
  are: "ہیں",
  was: "تھا",
  were: "تھے",
  will: "گا",
  be: "ہونا",
  have: "ہے",
  has: "ہے",
  had: "تھا",
  do: "کرنا",
  does: "کرتا",
  did: "کیا",
  can: "سکتا",
  could: "سکتا تھا",
  should: "چاہیے",
  would: "گا",
  may: "ہو سکتا",
  might: "ہو سکتا",
  must: "ضروری",
  shall: "گا",

  // Pronouns
  i: "میں",
  you: "آپ",
  he: "وہ",
  she: "وہ",
  it: "یہ",
  we: "ہم",
  they: "وہ",
  this: "یہ",
  that: "وہ",
  these: "یہ",
  those: "وہ",

  // Common nouns
  time: "وقت",
  person: "شخص",
  people: "لوگ",
  way: "طریقہ",
  day: "دن",
  man: "آدمی",
  woman: "عورت",
  child: "بچہ",
  world: "دنیا",
  life: "زندگی",
  hand: "ہاتھ",
  part: "حصہ",
  place: "جگہ",
  work: "کام",
  week: "ہفتہ",
  case: "معاملہ",
  point: "نقطہ",
  government: "حکومت",
  company: "کمپنی",
  number: "نمبر",
  group: "گروپ",
  problem: "مسئلہ",
  fact: "حقیقت",
  money: "پیسہ",
  business: "کاروبار",
  service: "خدمت",
  thing: "چیز",
  area: "علاقہ",
  water: "پانی",
  room: "کمرہ",
  family: "خاندان",
  friend: "دوست",
  house: "گھر",
  school: "سکول",
  country: "ملک",
  state: "ریاست",
  city: "شہر",
  community: "کمیونٹی",
  name: "نام",
  student: "طالب علم",
  month: "مہینہ",
  year: "سال",
  book: "کتاب",
  eye: "آنکھ",
  job: "نوکری",
  word: "لفظ",
  issue: "مسئلہ",
  side: "طرف",
  kind: "قسم",
  head: "سر",
  system: "نظام",
  program: "پروگرام",
  question: "سوال",
  right: "حق",
  data: "ڈیٹا",
  food: "کھانا",
  source: "ذریعہ",
  article: "مضمون",
  author: "مصنف",
  new: "نیا",
  research: "تحقیق",
  study: "مطالعہ",
  report: "رپورٹ",
  information: "معلومات",
  technology: "ٹیکنالوجی",
  development: "ترقی",
  market: "بازار",
  industry: "صنعت",
  product: "پروڈکٹ",
  customer: "کسٹمر",
  management: "انتظام",
  team: "ٹیم",
  project: "منصوبہ",
  result: "نتیجہ",
  process: "عمل",
  method: "طریقہ",
  approach: "نقطہ نظر",
  solution: "حل",
  strategy: "حکمت عملی",
  goal: "مقصد",
  objective: "مقصد",
  plan: "منصوبہ",
  policy: "پالیسی",
  decision: "فیصلہ",
  action: "عمل",
  activity: "سرگرمی",
  event: "واقعہ",
  meeting: "میٹنگ",
  conference: "کانفرنس",
  discussion: "بحث",
  analysis: "تجزیہ",
  review: "جائزہ",
  assessment: "تشخیص",
  evaluation: "تشخیص",
  performance: "کارکردگی",
  quality: "معیار",
  standard: "معیار",
  level: "سطح",
  rate: "شرح",
  price: "قیمت",
  cost: "لاگت",
  value: "قیمت",
  benefit: "فائدہ",
  advantage: "فائدہ",
  opportunity: "موقع",
  challenge: "چیلنج",
  risk: "خطرہ",
  safety: "حفاظت",
  security: "سیکیورٹی",
  health: "صحت",
  care: "دیکھ بھال",
  support: "مدد",
  help: "مدد",
  training: "تربیت",
  education: "تعلیم",
  learning: "سیکھنا",
  knowledge: "علم",
  skill: "مہارت",
  experience: "تجربہ",
  practice: "مشق",
  example: "مثال",
  model: "ماڈل",
  design: "ڈیزائن",
  structure: "ڈھانچہ",
  organization: "تنظیم",
  institution: "ادارہ",
  agency: "ایجنسی",
  department: "شعبہ",
  office: "دفتر",
  center: "مرکز",
  facility: "سہولت",
  equipment: "سامان",
  tool: "آلہ",
  machine: "مشین",
  device: "آلہ",
  computer: "کمپیوٹر",
  software: "سافٹ ویئر",
  application: "ایپلیکیشن",
  website: "ویب سائٹ",
  internet: "انٹرنیٹ",
  network: "نیٹ ورک",
  communication: "رابطہ",
  message: "پیغام",
  email: "ای میل",
  phone: "فون",
  call: "کال",
  presentation: "پیشکش",
  document: "دستاویز",
  file: "فائل",
  record: "ریکارڈ",
  database: "ڈیٹابیس",
  table: "ٹیبل",
  list: "فہرست",
  item: "آئٹم",
  element: "عنصر",
  component: "جزو",
  feature: "خصوصیت",
  function: "فنکشن",
  operation: "آپریشن",
  task: "کام",
  role: "کردار",
  responsibility: "ذمہ داری",
  duty: "فرض",
  requirement: "ضرورت",
  need: "ضرورت",
  demand: "مانگ",
  request: "درخواست",
  order: "آرڈر",
  instruction: "ہدایت",
  direction: "سمت",
  guide: "رہنمائی",
  manual: "دستی",
  tutorial: "ٹیوٹوریل",
  course: "کورس",
  class: "کلاس",
  lesson: "سبق",
  subject: "موضوع",
  topic: "موضوع",
  theme: "موضوع",
  content: "مواد",
  material: "مواد",
  resource: "وسائل",
  supply: "فراہمی",
  stock: "اسٹاک",
  inventory: "انوینٹری",
  goods: "سامان",
  piece: "ٹکڑا",
  unit: "یونٹ",
  package: "پیکج",
  box: "ڈبہ",
  container: "کنٹینر",
  bag: "بیگ",
  bottle: "بوتل",
  cup: "کپ",
  glass: "گلاس",
  plate: "پلیٹ",
  bowl: "پیالہ",
  spoon: "چمچ",
  knife: "چاقو",
  fork: "کانٹا",

  // Adjectives
  good: "اچھا",
  great: "عظیم",
  small: "چھوٹا",
  large: "بڑا",
  big: "بڑا",
  long: "لمبا",
  short: "چھوٹا",
  high: "اونچا",
  low: "نیچا",
  old: "پرانا",
  young: "جوان",
  important: "اہم",
  different: "مختلف",
  same: "ویسا ہی",
  right: "صحیح",
  wrong: "غلط",
  true: "سچ",
  false: "جھوٹ",
  real: "حقیقی",
  possible: "ممکن",
  available: "دستیاب",
  free: "مفت",
  open: "کھلا",
  close: "بند",
  easy: "آسان",
  hard: "مشکل",
  simple: "آسان",
  complex: "پیچیدہ",
  clear: "صاف",
  dark: "اندھیرا",
  light: "روشنی",
  heavy: "بھاری",
  strong: "مضبوط",
  weak: "کمزور",
  fast: "تیز",
  slow: "آہستہ",
  quick: "جلدی",
  early: "جلدی",
  late: "دیر",
  hot: "گرم",
  cold: "ٹھنڈا",
  warm: "گرم",
  cool: "ٹھنڈا",
  beautiful: "خوبصورت",
  nice: "اچھا",
  fine: "ٹھیک",
  bad: "برا",
  terrible: "خوفناک",
  wonderful: "شاندار",
  amazing: "حیرت انگیز",
  excellent: "بہترین",
  perfect: "کامل",
  special: "خاص",
  normal: "عام",
  regular: "باقاعدہ",
  common: "عام",
  rare: "نایاب",
  unique: "منفرد",
  popular: "مقبول",
  famous: "مشہور",
  successful: "کامیاب",
  effective: "مؤثر",
  efficient: "موثر",
  useful: "مفید",
  helpful: "مددگار",
  valuable: "قیمتی",
  expensive: "مہنگا",
  cheap: "سستا",
  rich: "امیر",
  poor: "غریب",
  full: "بھرا",
  empty: "خالی",
  complete: "مکمل",
  finished: "ختم",
  ready: "تیار",
  busy: "مصروف",
  active: "فعال",
  quiet: "خاموش",
  loud: "بلند",
  soft: "نرم",
  smooth: "ہموار",
  rough: "کھردرا",
  sharp: "تیز",
  safe: "محفوظ",
  dangerous: "خطرناک",
  serious: "سنجیدہ",
  funny: "مضحکہ خیز",
  happy: "خوش",
  sad: "اداس",
  angry: "ناراض",
  excited: "پرجوش",
  worried: "پریشان",
  surprised: "حیران",
  interested: "دلچسپ",
  boring: "بورنگ",
  tired: "تھکا",
  sick: "بیمار",
  healthy: "صحت مند",
  comfortable: "آرام دہ",
  uncomfortable: "تکلیف دہ",
  pleasant: "خوشگوار",
  unpleasant: "ناخوشگوار",
  friendly: "دوستانہ",
  kind: "مہربان",
  nice: "اچھا",
  polite: "مہذب",
  rude: "بدتمیز",
  honest: "ایمان دار",
  smart: "ہوشیار",
  intelligent: "ذہین",
  stupid: "بیوقوف",
  crazy: "پاگل",
  strange: "عجیب",
  weird: "عجیب",
  normal: "عام",
  typical: "عام",
  unusual: "غیر معمولی",
  extraordinary: "غیر معمولی",
  ordinary: "عام",
  standard: "معیاری",
  basic: "بنیادی",
  advanced: "اعلیٰ",
  professional: "پیشہ ورانہ",
  personal: "ذاتی",
  private: "نجی",
  public: "عوامی",
  general: "عام",
  specific: "مخصوص",
  particular: "خاص",
  individual: "انفرادی",
  single: "واحد",
  double: "دوہرا",
  multiple: "متعدد",
  several: "کئی",
  many: "بہت",
  few: "کم",
  little: "تھوڑا",
  much: "بہت",
  more: "زیادہ",
  most: "سب سے زیادہ",
  less: "کم",
  least: "سب سے کم",
  better: "بہتر",
  best: "بہترین",
  worse: "بدتر",
  worst: "بدترین",
  first: "پہلا",
  second: "دوسرا",
  third: "تیسرا",
  last: "آخری",
  next: "اگلا",
  previous: "پچھلا",
  current: "موجودہ",
  recent: "حالیہ",
  future: "مستقبل",
  past: "ماضی",
  present: "حال",
  modern: "جدید",
  traditional: "روایتی",
  ancient: "قدیم",
  historical: "تاریخی",
  cultural: "ثقافتی",
  social: "سماجی",
  political: "سیاسی",
  economic: "اقتصادی",
  financial: "مالی",
  legal: "قانونی",
  medical: "طبی",
  technical: "تکنیکی",
  scientific: "سائنسی",
  educational: "تعلیمی",
  environmental: "ماحولیاتی",
  natural: "قدرتی",
  artificial: "مصنوعی",
  digital: "ڈیجیٹل",
  electronic: "الیکٹرانک",
  mechanical: "میکانیکی",
  automatic: "خودکار",
  physical: "جسمانی",
  mental: "ذہنی",
  emotional: "جذباتی",
  spiritual: "روحانی",
  religious: "مذہبی",
  moral: "اخلاقی",
  ethical: "اخلاقی",
  practical: "عملی",
  theoretical: "نظریاتی",
  creative: "تخلیقی",
  innovative: "جدید",
  original: "اصل",
  similar: "ملتا جلتا",
  identical: "یکساں",
  equal: "برابر",
  equivalent: "مساوی",
  comparable: "موازنہ",
  relative: "رشتہ دار",
  absolute: "مطلق",
  total: "کل",
  partial: "جزوی",
  incomplete: "نامکمل",
  perfect: "کامل",
  imperfect: "نامکمل",
  accurate: "درست",
  inaccurate: "غلط",
  correct: "صحیح",
  incorrect: "غلط",
  exact: "بالکل",
  approximate: "تقریبی",
  precise: "درست",
  vague: "مبہم",
  unclear: "غیر واضح",
  obvious: "واضح",
  hidden: "چھپا",
  visible: "نظر آنے والا",
  invisible: "نظر نہ آنے والا",
  apparent: "ظاہر",
  secret: "خفیہ",
  confidential: "خفیہ",
  official: "سرکاری",
  unofficial: "غیر سرکاری",
  formal: "رسمی",
  informal: "غیر رسمی",
  direct: "براہ راست",
  indirect: "بالواسطہ",
  immediate: "فوری",
  delayed: "تاخیر",
  instant: "فوری",
  gradual: "بتدریج",
  sudden: "اچانک",
  urgent: "فوری",
  emergency: "ہنگامی",
  critical: "نازک",
  minor: "معمولی",
  major: "بڑا",
  significant: "اہم",
  insignificant: "غیر اہم",
  relevant: "متعلقہ",
  irrelevant: "غیر متعلقہ",
  appropriate: "مناسب",
  inappropriate: "نامناسب",
  suitable: "موزوں",
  unsuitable: "نامناسب",
  proper: "مناسب",
  improper: "نامناسب",
  reasonable: "معقول",
  unreasonable: "غیر معقول",
  logical: "منطقی",
  illogical: "غیر منطقی",
  rational: "عقلی",
  irrational: "غیر عقلی",
  sensible: "سمجھدار",
  nonsensical: "بے معنی",
  meaningful: "بامعنی",
  meaningless: "بے معنی",
  useful: "مفید",
  useless: "بے فائدہ",
  helpful: "مددگار",
  unhelpful: "غیر مددگار",
  beneficial: "فائدہ مند",
  harmful: "نقصان دہ",
  positive: "مثبت",
  negative: "منفی",
  constructive: "تعمیری",
  destructive: "تباہ کن",
  productive: "پیداواری",
  unproductive: "غیر پیداواری",
  efficient: "موثر",
  inefficient: "غیر موثر",
  effective: "مؤثر",
  ineffective: "غیر مؤثر",
  successful: "کامیاب",
  unsuccessful: "ناکام",
  profitable: "منافع بخش",
  unprofitable: "غیر منافع بخش",
  advantageous: "فائدہ مند",
  disadvantageous: "نقصان دہ",
  favorable: "سازگار",
  unfavorable: "غیر سازگار",
  convenient: "آسان",
  inconvenient: "مشکل",
  comfortable: "آرام دہ",
  uncomfortable: "تکلیف دہ",
  pleasant: "خوشگوار",
  unpleasant: "ناخوشگوار",
  enjoyable: "لطف انگیز",
  unenjoyable: "بے لطف",
  interesting: "دلچسپ",
  uninteresting: "بے دلچسپ",
  exciting: "پرجوش",
  boring: "بورنگ",
  entertaining: "تفریحی",
  educational: "تعلیمی",
  informative: "معلوماتی",
  instructive: "تعلیمی",
  inspiring: "متاثر کن",
  motivating: "حوصلہ افزا",
  encouraging: "حوصلہ افزا",
  discouraging: "حوصلہ شکن",
  supportive: "مددگار",
  unsupportive: "غیر مددگار",
  cooperative: "تعاون",
  uncooperative: "غیر تعاون",
  friendly: "دوستانہ",
  unfriendly: "غیر دوستانہ",
  kind: "مہربان",
  unkind: "بے رحم",
  generous: "فیاض",
  selfish: "خودغرض",
  honest: "ایمان دار",
  dishonest: "بے ایمان",
  trustworthy: "قابل اعتماد",
  untrustworthy: "غیر قابل اعتماد",
  reliable: "قابل اعتماد",
  unreliable: "غیر قابل اعتماد",
  responsible: "ذمہ دار",
  irresponsible: "غیر ذمہ دار",
  mature: "بالغ",
  immature: "نابالغ",
  experienced: "تجربہ کار",
  inexperienced: "غیر تجربہ کار",
  skilled: "ہنر مند",
  unskilled: "غیر ہنر مند",
  qualified: "اہل",
  unqualified: "غیر اہل",
  competent: "قابل",
  incompetent: "نا اہل",
  capable: "قابل",
  incapable: "نا اہل",
  able: "قابل",
  unable: "نا قابل",
  talented: "باصلاحیت",
  untalented: "بے صلاحیت",
  gifted: "ہونہار",
  creative: "تخلیقی",
  artistic: "فنکارانہ",
  musical: "موسیقی",
  athletic: "کھیل",
  academic: "تعلیمی",
  intellectual: "دانشورانہ",
  intelligent: "ذہین",
  smart: "ہوشیار",
  clever: "چالاک",
  wise: "دانا",
  foolish: "بیوقوف",
  stupid: "احمق",
  ignorant: "جاہل",
  knowledgeable: "علم والا",
  educated: "تعلیم یافتہ",
  uneducated: "غیر تعلیم یافتہ",
  literate: "پڑھا لکھا",
  illiterate: "ان پڑھ",
  cultured: "مہذب",
  uncultured: "غیر مہذب",
  civilized: "مہذب",
  uncivilized: "غیر مہذب",
  polite: "مہذب",
  impolite: "بدتمیز",
  rude: "بدتمیز",
  respectful: "احترام",
  disrespectful: "بے احترامی",
  obedient: "فرمانبردار",
  disobedient: "نافرمان",
  disciplined: "منضبط",
  undisciplined: "غیر منضبط",
  organized: "منظم",
  disorganized: "غیر منظم",
  neat: "صاف",
  messy: "گندا",
  clean: "صاف",
  dirty: "گندا",
  pure: "خالص",
  impure: "ناپاک",
  fresh: "تازہ",
  stale: "باسی",
  healthy: "صحت مند",
  unhealthy: "غیر صحت مند",
  fit: "تندرست",
  unfit: "غیر تندرست",
  strong: "مضبوط",
  weak: "کمزور",
  powerful: "طاقتور",
  powerless: "بے طاقت",
  energetic: "پرجوش",
  lethargic: "سست",
  active: "فعال",
  inactive: "غیر فعال",
  busy: "مصروف",
  idle: "بیکار",
  productive: "پیداواری",
  lazy: "سست",
  hardworking: "محنتی",
  dedicated: "وقف",
  committed: "پابند",
  loyal: "وفادار",
  disloyal: "بے وفا",
  faithful: "وفادار",
  unfaithful: "بے وفا",
  devoted: "وقف",
  passionate: "جذباتی",
  enthusiastic: "پرجوش",
  eager: "بے چین",
  reluctant: "ہچکچاہٹ",
  willing: "راضی",
  unwilling: "ناراض",
  ready: "تیار",
  unready: "غیر تیار",
  prepared: "تیار",
  unprepared: "غیر تیار",
  careful: "احتیاط",
  careless: "لاپرواہ",
  cautious: "محتاط",
  reckless: "لاپرواہ",
  safe: "محفوظ",
  unsafe: "غیر محفوظ",
  secure: "محفوظ",
  insecure: "غیر محفوظ",
  confident: "اعتماد",
  unconfident: "بے اعتماد",
  sure: "یقین",
  unsure: "غیر یقین",
  certain: "یقین",
  uncertain: "غیر یقین",
  definite: "قطعی",
  indefinite: "غیر قطعی",
  fixed: "مقرر",
  flexible: "لچکدار",
  rigid: "سخت",
  soft: "نرم",
  hard: "سخت",
  tough: "سخت",
  gentle: "نرم",
  rough: "کھردرا",
  smooth: "ہموار",
  sharp: "تیز",
  dull: "کند",
  bright: "روشن",
  dim: "مدھم",
  light: "ہلکا",
  dark: "اندھیرا",
  colorful: "رنگین",
  colorless: "بے رنگ",
  beautiful: "خوبصورت",
  ugly: "بدصورت",
  attractive: "دلکش",
  unattractive: "غیر دلکش",
  pretty: "خوبصورت",
  handsome: "خوبصورت",
  gorgeous: "خوبصورت",
  stunning: "حیرت انگیز",
  elegant: "خوبصورت",
  stylish: "انداز",
  fashionable: "فیشن",
  trendy: "جدید",
  modern: "جدید",
  contemporary: "عصری",
  "up-to-date": "جدید",
  outdated: "پرانا",
  "old-fashioned": "پرانے انداز",
  traditional: "روایتی",
  conventional: "روایتی",
  classic: "کلاسک",
  vintage: "پرانا",
  antique: "قدیم",
  ancient: "قدیم",
  historic: "تاریخی",
  legendary: "افسانوی",
  famous: "مشہور",
  "well-known": "معروف",
  popular: "مقبول",
  unpopular: "غیر مقبول",
  common: "عام",
  uncommon: "غیر عام",
  rare: "نایاب",
  scarce: "کم",
  abundant: "کثیر",
  plentiful: "بہت",
  numerous: "متعدد",
  countless: "بے شمار",
  infinite: "لامحدود",
  limited: "محدود",
  unlimited: "غیر محدود",
  boundless: "لامحدود",
  endless: "لامتناہی",
  eternal: "ابدی",
  temporary: "عارضی",
  permanent: "مستقل",
  constant: "مستقل",
  variable: "متغیر",
  stable: "مستحکم",
  unstable: "غیر مستحکم",
  steady: "مستحکم",
  unsteady: "غیر مستحکم",
  consistent: "مستقل",
  inconsistent: "غیر مستقل",
  regular: "باقاعدہ",
  irregular: "غیر باقاعدہ",
  normal: "عام",
  abnormal: "غیر عام",
  typical: "عام",
  atypical: "غیر عام",
  standard: "معیاری",
  "non-standard": "غیر معیاری",
  average: "اوسط",
  "above-average": "اوسط سے اوپر",
  "below-average": "اوسط سے نیچے",
  exceptional: "غیر معمولی",
  extraordinary: "غیر معمولی",
  remarkable: "قابل ذکر",
  unremarkable: "غیر قابل ذکر",
  notable: "قابل ذکر",
  outstanding: "بہترین",
  excellent: "بہترین",
  superior: "اعلیٰ",
  inferior: "کم تر",
  "high-quality": "اعلیٰ معیار",
  "low-quality": "کم معیار",
  premium: "پریمیم",
  luxury: "عیش و آرام",
  deluxe: "ڈیلکس",
  basic: "بنیادی",
  simple: "آسان",
  complex: "پیچیدہ",
  complicated: "پیچیدہ",
  difficult: "مشکل",
  easy: "آسان",
  effortless: "بے محنت",
  challenging: "چیلنجنگ",
  demanding: "مطالبہ",
  stressful: "تناؤ",
  relaxing: "آرام دہ",
  peaceful: "پرامن",
  calm: "پرسکون",
  quiet: "خاموش",
  silent: "خاموش",
  noisy: "شور",
  loud: "بلند",
  soft: "نرم",
  gentle: "نرم",
  harsh: "سخت",
  severe: "سخت",
  mild: "ہلکا",
  moderate: "اعتدال",
  extreme: "انتہائی",
  intense: "شدید",
  weak: "کمزور",
  strong: "مضبوط",
  powerful: "طاقتور",
  mighty: "طاقتور",
  enormous: "بہت بڑا",
  huge: "بہت بڑا",
  massive: "بہت بڑا",
  gigantic: "بہت بڑا",
  tiny: "چھوٹا",
  miniature: "چھوٹا",
  microscopic: "خردبینی",
  visible: "نظر آنے والا",
  obvious: "واضح",
  clear: "صاف",
  transparent: "شفاف",
  opaque: "غیر شفاف",
  translucent: "نیم شفاف",
  solid: "ٹھوس",
  liquid: "مائع",
  gas: "گیس",
  frozen: "منجمد",
  melted: "پگھلا",
  boiled: "ابلا",
  cooked: "پکا",
  raw: "کچا",
  fresh: "تازہ",
  rotten: "سڑا",
  spoiled: "خراب",
  preserved: "محفوظ",
  canned: "ڈبہ بند",
  dried: "خشک",
  wet: "گیلا",
  dry: "خشک",
  moist: "نم",
  damp: "نم",
  soaked: "بھیگا",
  flooded: "سیلاب زدہ",
  drought: "خشک سالی",
  sunny: "دھوپ",
  cloudy: "ابر آلود",
  rainy: "بارش",
  snowy: "برف",
  windy: "ہوا",
  stormy: "طوفان",
  foggy: "دھند",
  misty: "دھند",
  overcast: "ابر آلود",
  humid: "نمی",
  arid: "خشک",
  tropical: "اشنکٹبندیی",
  arctic: "قطبی",
  temperate: "معتدل",
  seasonal: "موسمی",
  annual: "سالانہ",
  monthly: "ماہانہ",
  weekly: "ہفتہ وار",
  daily: "روزانہ",
  hourly: "گھنٹہ وار",
  frequent: "بار بار",
  occasional: "کبھی کبھار",
  rare: "نایاب",
  never: "کبھی نہیں",
  always: "ہمیشہ",
  sometimes: "کبھی کبھی",
  often: "اکثر",
  seldom: "شاذ و نادر",
  usually: "عام طور پر",
  generally: "عام طور پر",
  typically: "عام طور پر",
  normally: "عام طور پر",
  commonly: "عام طور پر",
  frequently: "اکثر",
  regularly: "باقاعدگی سے",
  consistently: "مستقل",
  constantly: "مستقل",
  continuously: "مسلسل",
  repeatedly: "بار بار",
  again: "دوبارہ",
  once: "ایک بار",
  twice: "دو بار",
  thrice: "تین بار",
  multiple: "متعدد",
  single: "واحد",
  double: "دوہرا",
  triple: "تین گنا",
  quadruple: "چار گنا",
  half: "آدھا",
  quarter: "چوتھائی",
  third: "تہائی",
  whole: "پورا",
  entire: "پورا",
  full: "بھرا",
  empty: "خالی",
  vacant: "خالی",
  occupied: "قبضے میں",
  available: "دستیاب",
  unavailable: "غیر دستیاب",
  accessible: "قابل رسائی",
  inaccessible: "ناقابل رسائی",
  reachable: "پہنچنے کے قابل",
  unreachable: "ناقابل رسائی",
  approachable: "قابل رسائی",
  unapproachable: "ناقابل رسائی",
  friendly: "دوستانہ",
  hostile: "دشمنانہ",
  aggressive: "جارحانہ",
  passive: "غیر فعال",
  active: "فعال",
  reactive: "رد عمل",
  proactive: "پیش قدمی",
  interactive: "تعاملی",

  // Verbs
  go: "جانا",
  come: "آنا",
  see: "دیکھنا",
  know: "جاننا",
  get: "حاصل کرنا",
  give: "دینا",
  take: "لینا",
  make: "بنانا",
  think: "سوچنا",
  say: "کہنا",
  tell: "بتانا",
  ask: "پوچھنا",
  answer: "جواب دینا",
  speak: "بولنا",
  talk: "بات کرنا",
  listen: "سننا",
  hear: "سننا",
  read: "پڑھنا",
  write: "لکھنا",
  learn: "سیکھنا",
  teach: "سکھانا",
  study: "مطالعہ کرنا",
  understand: "سمجھنا",
  remember: "یاد رکھنا",
  forget: "بھولنا",
  believe: "یقین کرنا",
  hope: "امید کرنا",
  want: "چاہنا",
  need: "ضرورت ہونا",
  like: "پسند کرنا",
  love: "محبت کرنا",
  hate: "نفرت کرنا",
  enjoy: "لطف اٹھانا",
  prefer: "ترجیح دینا",
  choose: "چننا",
  decide: "فیصلہ کرنا",
  try: "کوشش کرنا",
  attempt: "کوشش کرنا",
  succeed: "کامیاب ہونا",
  fail: "ناکام ہونا",
  win: "جیتنا",
  lose: "ہارنا",
  start: "شروع کرنا",
  begin: "شروع کرنا",
  finish: "ختم کرنا",
  end: "ختم کرنا",
  stop: "رکنا",
  continue: "جاری رکھنا",
  keep: "رکھنا",
  hold: "پکڑنا",
  carry: "اٹھانا",
  bring: "لانا",
  send: "بھیجنا",
  receive: "وصول کرنا",
  buy: "خریدنا",
  sell: "بیچنا",
  pay: "ادائیگی کرنا",
  cost: "قیمت ہونا",
  spend: "خرچ کرنا",
  save: "بچانا",
  earn: "کمانا",
  work: "کام کرنا",
  play: "کھیلنا",
  rest: "آرام کرنا",
  sleep: "سونا",
  wake: "جاگنا",
  eat: "کھانا",
  drink: "پینا",
  cook: "پکانا",
  clean: "صاف کرنا",
  wash: "دھونا",
  wear: "پہننا",
  put: "رکھنا",
  remove: "ہٹانا",
  open: "کھولنا",
  close: "بند کرنا",
  turn: "موڑنا",
  move: "حرکت کرنا",
  walk: "چلنا",
  run: "دوڑنا",
  jump: "کودنا",
  sit: "بیٹھنا",
  stand: "کھڑا ہونا",
  lie: "لیٹنا",
  fall: "گرنا",
  rise: "اٹھنا",
  climb: "چڑھنا",
  drive: "چلانا",
  travel: "سفر کرنا",
  visit: "ملاقات کرنا",
  meet: "ملنا",
  join: "شامل ہونا",
  leave: "چھوڑنا",
  stay: "رہنا",
  live: "رہنا",
  die: "مرنا",
  kill: "مارنا",
  hurt: "تکلیف دینا",
  help: "مدد کرنا",
  save: "بچانا",
  protect: "محفوظ رکھنا",
  attack: "حملہ کرنا",
  fight: "لڑنا",
  argue: "بحث کرنا",
  agree: "اتفاق کرنا",
  disagree: "اختلاف کرنا",
  accept: "قبول کرنا",
  refuse: "انکار کرنا",
  allow: "اجازت دینا",
  forbid: "منع کرنا",
  permit: "اجازت دینا",
  prevent: "روکنا",
  avoid: "بچنا",
  escape: "بھاگنا",
  catch: "پکڑنا",
  throw: "پھینکنا",
  pull: "کھینچنا",
  push: "دھکیلنا",
  lift: "اٹھانا",
  drop: "گرانا",
  break: "توڑنا",
  fix: "ٹھیک کرنا",
  repair: "مرمت کرنا",
  build: "بنانا",
  create: "تخلیق کرنا",
  destroy: "تباہ کرنا",
  change: "تبدیل کرنا",
  improve: "بہتر بنانا",
  develop: "ترقی کرنا",
  grow: "بڑھنا",
  increase: "بڑھانا",
  decrease: "کم کرنا",
  reduce: "کم کرنا",
  add: "شامل کرنا",
  subtract: "منہا کرنا",
  multiply: "ضرب دینا",
  divide: "تقسیم کرنا",
  calculate: "حساب کرنا",
  count: "گننا",
  measure: "ناپنا",
  weigh: "تولنا",
  compare: "موازنہ کرنا",
  contrast: "فرق کرنا",
  match: "میچ کرنا",
  fit: "فٹ کرنا",
  connect: "جوڑنا",
  disconnect: "الگ کرنا",
  attach: "لگانا",
  detach: "الگ کرنا",
  combine: "ملانا",
  separate: "الگ کرنا",
  mix: "ملانا",
  blend: "ملانا",
  stir: "ہلانا",
  shake: "ہلانا",
  pour: "ڈالنا",
  fill: "بھرنا",
  empty: "خالی کرنا",
  load: "لادنا",
  unload: "اتارنا",
  pack: "پیک کرنا",
  unpack: "کھولنا",
  wrap: "لپیٹنا",
  unwrap: "کھولنا",
  cover: "ڈھانپنا",
  uncover: "کھولنا",
  hide: "چھپانا",
  show: "دکھانا",
  reveal: "ظاہر کرنا",
  display: "دکھانا",
  present: "پیش کرنا",
  introduce: "تعارف کرانا",
  explain: "وضاحت کرنا",
  describe: "بیان کرنا",
  define: "تعین کرنا",
  identify: "شناخت کرنا",
  recognize: "پہچاننا",
  notice: "نوٹس کرنا",
  observe: "مشاہدہ کرنا",
  watch: "دیکھنا",
  look: "دیکھنا",
  search: "تلاش کرنا",
  find: "تلاش کرنا",
  discover: "دریافت کرنا",
  explore: "کھوج کرنا",
  investigate: "تحقیق کرنا",
  examine: "جانچنا",
  test: "ٹیسٹ کرنا",
  check: "چیک کرنا",
  verify: "تصدیق کرنا",
  confirm: "تصدیق کرنا",
  prove: "ثابت کرنا",
  demonstrate: "ثابت کرنا",
  show: "دکھانا",
  indicate: "اشارہ کرنا",
  point: "اشارہ کرنا",
  direct: "ہدایت دینا",
  guide: "رہنمائی کرنا",
  lead: "رہنمائی کرنا",
  follow: "پیروی کرنا",
  track: "ٹریک کرنا",
  trace: "نشان لگانا",
  monitor: "نگرانی کرنا",
  supervise: "نگرانی کرنا",
  manage: "انتظام کرنا",
  control: "کنٹرول کرنا",
  operate: "چلانا",
  handle: "سنبھالنا",
  deal: "نمٹنا",
  cope: "نمٹنا",
  struggle: "جدوجہد کرنا",
  compete: "مقابلہ کرنا",
  challenge: "چیلنج کرنا",
  face: "سامنا کرنا",
  confront: "سامنا کرنا",
  encounter: "سامنا کرنا",
  experience: "تجربہ کرنا",
  undergo: "گزارنا",
  suffer: "تکلیف اٹھانا",
  endure: "برداشت کرنا",
  tolerate: "برداشت کرنا",
  bear: "برداشت کرنا",
  support: "مدد کرنا",
  assist: "مدد کرنا",
  aid: "مدد کرنا",
  serve: "خدمت کرنا",
  provide: "فراہم کرنا",
  supply: "فراہم کرنا",
  offer: "پیش کرنا",
  suggest: "تجویز کرنا",
  recommend: "سفارش کرنا",
  advise: "مشورہ دینا",
  warn: "خبردار کرنا",
  inform: "اطلاع دینا",
  notify: "اطلاع دینا",
  announce: "اعلان کرنا",
  declare: "اعلان کرنا",
  state: "بیان کرنا",
  claim: "دعویٰ کرنا",
  assert: "زور دینا",
  insist: "اصرار کرنا",
  demand: "مطالبہ کرنا",
  require: "ضرورت ہونا",
  request: "درخواست کرنا",
  order: "حکم دینا",
  command: "حکم دینا",
  instruct: "ہدایت دینا",
  direct: "ہدایت دینا",
  assign: "تفویض کرنا",
  appoint: "مقرر کرنا",
  hire: "ملازمت دینا",
  employ: "ملازمت دینا",
  fire: "برطرف کرنا",
  dismiss: "برطرف کرنا",
  quit: "چھوڑنا",
  resign: "استعفیٰ دینا",
  retire: "ریٹائر ہونا",
  graduate: "فارغ التحصیل ہونا",
  qualify: "اہل ہونا",
  pass: "پاس کرنا",
  fail: "فیل ہونا",
  score: "اسکور کرنا",
  achieve: "حاصل کرنا",
  accomplish: "مکمل کرنا",
  complete: "مکمل کرنا",
  fulfill: "پورا کرنا",
  satisfy: "مطمئن کرنا",
  please: "خوش کرنا",
  disappoint: "مایوس کرنا",
  upset: "پریشان کرنا",
  annoy: "تنگ کرنا",
  bother: "تنگ کرنا",
  disturb: "پریشان کرنا",
  interrupt: "مداخلت کرنا",
  interfere: "مداخلت کرنا",
  involve: "شامل کرنا",
  participate: "حصہ لینا",
  contribute: "حصہ ڈالنا",
  donate: "عطیہ دینا",
  share: "بانٹنا",
  distribute: "تقسیم کرنا",
  spread: "پھیلانا",
  expand: "پھیلانا",
  extend: "بڑھانا",
  stretch: "کھینچنا",
  reach: "پہنچنا",
  arrive: "پہنچنا",
  depart: "روانہ ہونا",
  return: "واپس آنا",
  enter: "داخل ہونا",
  exit: "نکلنا",
  approach: "قریب آنا",
  retreat: "پیچھے ہٹنا",
  advance: "آگے بڑھنا",
  progress: "ترقی کرنا",
  proceed: "آگے بڑھنا",
  continue: "جاری رکھنا",
  maintain: "برقرار رکھنا",
  preserve: "محفوظ رکھنا",
  conserve: "محفوظ رکھنا",
  waste: "ضائع کرنا",
  lose: "کھونا",
  miss: "چوکنا",
  skip: "چھوڑنا",
  ignore: "نظرانداز کرنا",
  neglect: "غفلت کرنا",
  abandon: "چھوڑ دینا",
  desert: "چھوڑ دینا",
  betray: "دھوکہ دینا",
  cheat: "دھوکہ دینا",
  lie: "جھوٹ بولنا",
  steal: "چوری کرنا",
  rob: "لوٹنا",
  borrow: "ادھار لینا",
  lend: "ادھار دینا",
  owe: "قرض ہونا",
  repay: "واپس کرنا",
  return: "واپس کرنا",
  exchange: "تبادلہ کرنا",
  trade: "تجارت کرنا",
  negotiate: "بات چیت کرنا",
  bargain: "مول بھاؤ کرنا",
  deal: "معاملہ کرنا",
  contract: "معاہدہ کرنا",
  sign: "دستخط کرنا",
  approve: "منظور کرنا",
  reject: "مسترد کرنا",
  cancel: "منسوخ کرنا",
  postpone: "ملتوی کرنا",
  delay: "تاخیر کرنا",
  hurry: "جلدی کرنا",
  rush: "جلدی کرنا",
  wait: "انتظار کرنا",
  expect: "توقع کرنا",
  anticipate: "توقع کرنا",
  predict: "پیش گوئی کرنا",
  forecast: "پیش گوئی کرنا",
  estimate: "اندازہ لگانا",
  guess: "اندازہ لگانا",
  assume: "فرض کرنا",
  suppose: "فرض کرنا",
  imagine: "تصور کرنا",
  dream: "خواب دیکھنا",
  wish: "خواہش کرنا",
  desire: "خواہش کرنا",
  crave: "لالچ کرنا",
  long: "تڑپنا",
  yearn: "تڑپنا",
  regret: "پچھتانا",
  apologize: "معافی مانگنا",
  forgive: "معاف کرنا",
  excuse: "معاف کرنا",
  pardon: "معاف کرنا",
  blame: "الزام لگانا",
  accuse: "الزام لگانا",
  criticize: "تنقید کرنا",
  praise: "تعریف کرنا",
  compliment: "تعریف کرنا",
  thank: "شکریہ کہنا",
  appreciate: "قدر کرنا",
  value: "قدر کرنا",
  respect: "احترام کرنا",
  admire: "تعریف کرنا",
  worship: "عبادت کرنا",
  pray: "دعا کرنا",
  bless: "برکت دینا",
  curse: "لعنت بھیجنا",
  swear: "قسم کھانا",
  promise: "وعدہ کرنا",
  commit: "عہد کرنا",
  dedicate: "وقف کرنا",
  devote: "وقف کرنا",
  sacrifice: "قربانی کرنا",
  risk: "خطرہ مول لینا",
  gamble: "جوا کھیلنا",
  bet: "شرط لگانا",
  wager: "شرط لگانا",
  stake: "داؤ لگانا",
  venture: "خطرہ مول لینا",
  speculate: "قیاس آرائی کرنا",
  calculate: "حساب کرنا",
  compute: "حساب کرنا",
  figure: "حساب کرنا",
  determine: "طے کرنا",
  resolve: "حل کرنا",
}
